### ISSUE TITLE
Test is failing without any error message

### ISSUE THREAD

**Issue by manuelbiermann** [Shopify/lighthouse-ci-action#12]
<img width="1102" alt="Screenshot 2021-07-20 at 22 35 07" src="https://user-images.githubusercontent.com/12250753/126391925-d84b6e74-c389-4306-b18a-8574a48c44eb.png">

**Comment by nikkisato** [comment]
I have this too

**Comment by charlespwd** [comment]
Is it failing at that step? If so it's probably that the app credentials are missing the product read permission.

If not, then I'd need to know exactly where it fails.

**Comment by nikkisato** [comment]
I have the same issue, I just went into my Shopify and gave the app credentials:
Product Listing and Products both read access just to be on the safe side and still fails and gets the same error message

**Comment by charlespwd** [comment]
Hiya, I think I've found what the problem was. It looks like the curl request was failing silently. This could happen for a multitude of reason but the one that comes to mind would be an invalid `store` configuration variable. 

Before, we assumed that the protocol (https://) was not part of this setting. If it was in there, the curl request would fail silently.

I'll also add code to make this not error out when this happens in the future, one shouldn't need to care about this.
